<a href="https://colab.research.google.com/github/Shivam9701/pytorch/blob/main/01_tensor_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

## Add, Subtract, Multiply Tensors

In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 2

tensor([3, 4, 5])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
## Tensor Multiplaction ->
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1,
tensor * tensor

tensor([1, 4, 9])

## Matrix Multiplication

In [ ]:
# The difference between element-wise multiplication and matrix multiplication is the addition of values.

# For our tensor variable with values [1, 2, 3]:

# Operation	Calculation	Code
# Element-wise multiplication	[1*1, 2*2, 3*3] = [1, 4, 9]	tensor * tensor
# Matrix multiplication	[1*1 + 2*2 + 3*3] = [14]	tensor.matmul(tensor)

torch.matmul(tensor, tensor)


tensor(14)

In [3]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)


In [ ]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
%%time
torch.matmul(tensor_A, tensor_B.T)

CPU times: user 821 µs, sys: 0 ns, total: 821 µs
Wall time: 666 µs


tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
## You can also use torch.mm() which is a short for torch.matmul().

torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
# Neural networks are full of matrix multiplications and dot products.

# The torch.nn.Linear() module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input x and a weights matrix A.

# y = x.{A^T} + b

# Where:

# x is the input to the layer (deep learning is a stack of layers like torch.nn.Linear() and others on top of each other).
# A is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "T", that's because the weights matrix gets transposed).
# Note: You might also often see W or another letter like X used to showcase the weights matrix.
# b is the bias term used to slightly offset the weights and inputs.
# y is the output (a manipulation of the input in the hopes to discover patterns in it).
# This is a linear function (you may have seen something like $y = mx+b$ in high school or elsewhere), and can be used to draw a straight line!

In [ ]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features =2, out_features = 6)

x = tensor_A
output = linear(x)

print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


## Finding min, max, mean, sum

In [5]:
## some methods such as torch.mean() require tensors to be in torch.float32 (the most common) or
## another specific datatype, otherwise the operation will fail.
x = torch.arange(0, 100, 10)

print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


## Positional

In [6]:
x.argmin(), x.argmax() # Return index where min and max occur

(tensor(0), tensor(9))

## Datatypes

In [7]:
x.dtype

torch.int64

In [8]:
x_16 = x.type(torch.float16)
x_16.dtype

torch.float16

In [9]:
x_8 = x.type(torch.int8)
x_8.dtype

torch.int8

## Reshaping

In [20]:
x = x.reshape((1, x.shape[0]))
x, x.shape, x.ndim

(tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]), torch.Size([1, 10]), 2)

In [24]:
z = x.view(1, 1, 10) # If View modified it changes original tensor
z[0,0] = 90
x, z

(tensor([[90, 90, 90, 90, 90, 90, 90, 90, 90, 90]]),
 tensor([[[90, 90, 90, 90, 90, 90, 90, 90, 90, 90]]]))

In [25]:
x = x.reshape(1, 10)
x

tensor([[90, 90, 90, 90, 90, 90, 90, 90, 90, 90]])

## Stacking

In [35]:
x_stacked = torch.stack([x, x, x, x], dim=0) # Stack on top of each other and increase dim by 1
x_stacked, x_stacked.shape, x.shape

(tensor([[[90, 90, 90, 90, 90, 90, 90, 90, 90, 90]],
 
         [[90, 90, 90, 90, 90, 90, 90, 90, 90, 90]],
 
         [[90, 90, 90, 90, 90, 90, 90, 90, 90, 90]],
 
         [[90, 90, 90, 90, 90, 90, 90, 90, 90, 90]]]),
 torch.Size([4, 1, 10]),
 torch.Size([1, 10]))

In [29]:
x_stacked2 = torch.stack([x, x, x, x], dim=1) # Stack side by side
x_stacked2, x_stacked2.shape, x.shape

(tensor([[[90, 90, 90, 90, 90, 90, 90, 90, 90, 90],
          [90, 90, 90, 90, 90, 90, 90, 90, 90, 90],
          [90, 90, 90, 90, 90, 90, 90, 90, 90, 90],
          [90, 90, 90, 90, 90, 90, 90, 90, 90, 90]]]),
 torch.Size([1, 4, 10]),
 torch.Size([1, 10]))

## torch.squeeze() - Remove the dimensions having val 1

In [30]:
## torch.squeeze

x_squeezed = x_stacked.squeeze()
x_squeezed, x_squeezed.shape

(tensor([[90, 90, 90, 90, 90, 90, 90, 90, 90, 90],
         [90, 90, 90, 90, 90, 90, 90, 90, 90, 90],
         [90, 90, 90, 90, 90, 90, 90, 90, 90, 90],
         [90, 90, 90, 90, 90, 90, 90, 90, 90, 90]]),
 torch.Size([4, 10]))

In [36]:
x_stacked = torch.stack([x_stacked, x_stacked])

print(x_stacked.shape)

x_squeezed = x_stacked.squeeze()
x_squeezed, x_squeezed.shape

torch.Size([2, 4, 1, 10])


(tensor([[[90, 90, 90, 90, 90, 90, 90, 90, 90, 90],
          [90, 90, 90, 90, 90, 90, 90, 90, 90, 90],
          [90, 90, 90, 90, 90, 90, 90, 90, 90, 90],
          [90, 90, 90, 90, 90, 90, 90, 90, 90, 90]],
 
         [[90, 90, 90, 90, 90, 90, 90, 90, 90, 90],
          [90, 90, 90, 90, 90, 90, 90, 90, 90, 90],
          [90, 90, 90, 90, 90, 90, 90, 90, 90, 90],
          [90, 90, 90, 90, 90, 90, 90, 90, 90, 90]]]),
 torch.Size([2, 4, 10]))

## And to do the reverse of torch.squeeze() you can use torch.unsqueeze() to add a dimension value of 1 at a specific index.

In [37]:
x_squeezed.unsqueeze(dim=0).shape

torch.Size([1, 2, 4, 10])