<a href="https://colab.research.google.com/github/Shivam9701/pytorch/blob/main/03_tensor_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [5]:
x = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]
    ]
])

x.shape

torch.Size([2, 3, 3])

In [6]:
x[:, 0] # 1st Row of every 2D Matix in whole 3D tensor

tensor([[ 1,  2,  3],
        [11, 12, 13]])

In [7]:
x[:, :, 0] # 1st Element of all rows of all 2D matrix in 3d tensor

tensor([[ 1,  4,  7],
        [11, 14, 17]])

In [8]:
import numpy as np

a = np.array([1, 2, 3])

tensor = torch.from_numpy(a).type(torch.float32) # Defaults to float64 because np def is f64|

tensor

tensor([1., 2., 3.])