<a href="https://colab.research.google.com/github/Shivam9701/pytorch/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Fri Sep 13 06:07:51 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch

torch.__version__

'2.4.0+cu121'

## Intro to Tensors

In [ ]:
# Create a Scalar - A scalar is a single number. It is a 0-dimensional tensor.

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.item(), scalar.ndim, scalar.shape # Get the Value of a Scalar and the n. of dims

(7, 0, torch.Size([]))

In [ ]:
# Create a vector - A vector is  1-dimensional tensor. It is a sequence of numbers.

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
# The number of dimensions of a tensor is the
# number of indices that are required to access a single element in the tensor.
# The shape of a tensor is the number of elements in each dimension of the tensor.

vector.ndim, vector.shape

(1, torch.Size([2]))

In [ ]:
# MATRIX

MATRIX = torch.tensor([[7, 8, 9],
                      [9, 10, 12]])
MATRIX

tensor([[ 7,  8,  9],
        [ 9, 10, 12]])

In [ ]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 3]))

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

In [ ]:
random = torch.rand(size = (3, 4))
random, random.dtype

(tensor([[0.4054, 0.2760, 0.7954, 0.4010],
         [0.9941, 0.3665, 0.0105, 0.3647],
         [0.6331, 0.9684, 0.8469, 0.5584]]),
 torch.float32)

In [ ]:
randImg = torch.rand((224, 224, 3))
randImg.shape, randImg.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zeros = torch.zeros(size = (3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
ones = torch.ones(size = (3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [ ]:
range_tensor = torch.arange(start = 0.1, end = 1.2, step = .1)
range_tensor, range_tensor.shape

(tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
         1.0000, 1.1000]),
 torch.Size([11]))

In [ ]:
float_32 = torch.tensor([7.0, 8.0, 9.0])

In [ ]:
float_16 = torch.tensor([7.0, 8.0, 9.0], dtype = torch.float16)
float_16, float_16.dtype

(tensor([7., 8., 9.], dtype=torch.float16), torch.float16)

### Tensor Info

In [ ]:
rand_tensor = torch.tensor([1, 2, 3], device='cpu')
rand_tensor.device, rand_tensor.dtype, rand_tensor.shape, rand_tensor

(device(type='cpu'), torch.int64, torch.Size([3]), tensor([1, 2, 3]))